//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.TareaPredeterminadaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="TareaPredeterminadaWS.TareaPredeterminadaWS")]
    public interface TareaPredeterminadaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/listarTareasPredeterm" +
            "inadasPorCategoriaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/listarTareasPredeterm" +
            "inadasPorCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaResponse listarTareasPredeterminadasPorCategoria(TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/listarTareasPredeterm" +
            "inadasPorCategoriaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/listarTareasPredeterm" +
            "inadasPorCategoriaResponse")]
        System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaResponse> listarTareasPredeterminadasPorCategoriaAsync(TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/actualizarTareaPredet" +
            "erminadaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/actualizarTareaPredet" +
            "erminadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaResponse actualizarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/actualizarTareaPredet" +
            "erminadaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/actualizarTareaPredet" +
            "erminadaResponse")]
        System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaResponse> actualizarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/insertarTareaPredeter" +
            "minadaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/insertarTareaPredeter" +
            "minadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaResponse insertarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/insertarTareaPredeter" +
            "minadaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/insertarTareaPredeter" +
            "minadaResponse")]
        System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaResponse> insertarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/eliminarTareaPredeter" +
            "minadaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/eliminarTareaPredeter" +
            "minadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaResponse eliminarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/eliminarTareaPredeter" +
            "minadaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/TareaPredeterminadaWS/eliminarTareaPredeter" +
            "minadaResponse")]
        System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaResponse> eliminarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int categoriaIdField;
        
        private string descripcionField;
        
        private string nombreField;
        
        private tareaPredeterminada[] tareasPredeterminadasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int categoriaId {
            get {
                return this.categoriaIdField;
            }
            set {
                this.categoriaIdField = value;
                this.RaisePropertyChanged("categoriaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tareasPredeterminadas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public tareaPredeterminada[] tareasPredeterminadas {
            get {
                return this.tareasPredeterminadasField;
            }
            set {
                this.tareasPredeterminadasField = value;
                this.RaisePropertyChanged("tareasPredeterminadas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class tareaPredeterminada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string descripcionField;
        
        private string fechaCreacionField;
        
        private int tareaPredeterminadaIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tareaPredeterminadaId {
            get {
                return this.tareaPredeterminadaIdField;
            }
            set {
                this.tareaPredeterminadaIdField = value;
                this.RaisePropertyChanged("tareaPredeterminadaId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTareasPredeterminadasPorCategoria", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTareasPredeterminadasPorCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.TareaPredeterminadaWS.categoria objCategoria;
        
        public listarTareasPredeterminadasPorCategoriaRequest() {
        }
        
        public listarTareasPredeterminadasPorCategoriaRequest(TableSoft.TareaPredeterminadaWS.categoria objCategoria) {
            this.objCategoria = objCategoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTareasPredeterminadasPorCategoriaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTareasPredeterminadasPorCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.TareaPredeterminadaWS.tareaPredeterminada[] @return;
        
        public listarTareasPredeterminadasPorCategoriaResponse() {
        }
        
        public listarTareasPredeterminadasPorCategoriaResponse(TableSoft.TareaPredeterminadaWS.tareaPredeterminada[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarTareaPredeterminada", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarTareaPredeterminadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada;
        
        public actualizarTareaPredeterminadaRequest() {
        }
        
        public actualizarTareaPredeterminadaRequest(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada) {
            this.objTareaPredeterminada = objTareaPredeterminada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarTareaPredeterminadaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarTareaPredeterminadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarTareaPredeterminadaResponse() {
        }
        
        public actualizarTareaPredeterminadaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTareaPredeterminada", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTareaPredeterminadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.TareaPredeterminadaWS.categoria objCategoria;
        
        public insertarTareaPredeterminadaRequest() {
        }
        
        public insertarTareaPredeterminadaRequest(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada, TableSoft.TareaPredeterminadaWS.categoria objCategoria) {
            this.objTareaPredeterminada = objTareaPredeterminada;
            this.objCategoria = objCategoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTareaPredeterminadaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTareaPredeterminadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTareaPredeterminadaResponse() {
        }
        
        public insertarTareaPredeterminadaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTareaPredeterminada", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTareaPredeterminadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada;
        
        public eliminarTareaPredeterminadaRequest() {
        }
        
        public eliminarTareaPredeterminadaRequest(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada) {
            this.objTareaPredeterminada = objTareaPredeterminada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTareaPredeterminadaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTareaPredeterminadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTareaPredeterminadaResponse() {
        }
        
        public eliminarTareaPredeterminadaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TareaPredeterminadaWSChannel : TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TareaPredeterminadaWSClient : System.ServiceModel.ClientBase<TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS>, TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS {
        
        public TareaPredeterminadaWSClient() {
        }
        
        public TareaPredeterminadaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TareaPredeterminadaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TareaPredeterminadaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TareaPredeterminadaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaResponse TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoria(TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaRequest request) {
            return base.Channel.listarTareasPredeterminadasPorCategoria(request);
        }
        
        public TableSoft.TareaPredeterminadaWS.tareaPredeterminada[] listarTareasPredeterminadasPorCategoria(TableSoft.TareaPredeterminadaWS.categoria objCategoria) {
            TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaRequest inValue = new TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaRequest();
            inValue.objCategoria = objCategoria;
            TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaResponse retVal = ((TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS)(this)).listarTareasPredeterminadasPorCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaResponse> TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaAsync(TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaRequest request) {
            return base.Channel.listarTareasPredeterminadasPorCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaResponse> listarTareasPredeterminadasPorCategoriaAsync(TableSoft.TareaPredeterminadaWS.categoria objCategoria) {
            TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaRequest inValue = new TableSoft.TareaPredeterminadaWS.listarTareasPredeterminadasPorCategoriaRequest();
            inValue.objCategoria = objCategoria;
            return ((TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS)(this)).listarTareasPredeterminadasPorCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaResponse TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS.actualizarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaRequest request) {
            return base.Channel.actualizarTareaPredeterminada(request);
        }
        
        public int actualizarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada) {
            TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaRequest inValue = new TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaRequest();
            inValue.objTareaPredeterminada = objTareaPredeterminada;
            TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaResponse retVal = ((TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS)(this)).actualizarTareaPredeterminada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaResponse> TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS.actualizarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaRequest request) {
            return base.Channel.actualizarTareaPredeterminadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaResponse> actualizarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada) {
            TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaRequest inValue = new TableSoft.TareaPredeterminadaWS.actualizarTareaPredeterminadaRequest();
            inValue.objTareaPredeterminada = objTareaPredeterminada;
            return ((TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS)(this)).actualizarTareaPredeterminadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaResponse TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS.insertarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaRequest request) {
            return base.Channel.insertarTareaPredeterminada(request);
        }
        
        public int insertarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada, TableSoft.TareaPredeterminadaWS.categoria objCategoria) {
            TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaRequest inValue = new TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaRequest();
            inValue.objTareaPredeterminada = objTareaPredeterminada;
            inValue.objCategoria = objCategoria;
            TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaResponse retVal = ((TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS)(this)).insertarTareaPredeterminada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaResponse> TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS.insertarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaRequest request) {
            return base.Channel.insertarTareaPredeterminadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaResponse> insertarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada, TableSoft.TareaPredeterminadaWS.categoria objCategoria) {
            TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaRequest inValue = new TableSoft.TareaPredeterminadaWS.insertarTareaPredeterminadaRequest();
            inValue.objTareaPredeterminada = objTareaPredeterminada;
            inValue.objCategoria = objCategoria;
            return ((TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS)(this)).insertarTareaPredeterminadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaResponse TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS.eliminarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaRequest request) {
            return base.Channel.eliminarTareaPredeterminada(request);
        }
        
        public int eliminarTareaPredeterminada(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada) {
            TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaRequest inValue = new TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaRequest();
            inValue.objTareaPredeterminada = objTareaPredeterminada;
            TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaResponse retVal = ((TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS)(this)).eliminarTareaPredeterminada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaResponse> TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS.eliminarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaRequest request) {
            return base.Channel.eliminarTareaPredeterminadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaResponse> eliminarTareaPredeterminadaAsync(TableSoft.TareaPredeterminadaWS.tareaPredeterminada objTareaPredeterminada) {
            TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaRequest inValue = new TableSoft.TareaPredeterminadaWS.eliminarTareaPredeterminadaRequest();
            inValue.objTareaPredeterminada = objTareaPredeterminada;
            return ((TableSoft.TareaPredeterminadaWS.TareaPredeterminadaWS)(this)).eliminarTareaPredeterminadaAsync(inValue);
        }
    }
}
