//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.ActivoFijoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="ActivoFijoWS.ActivoFijoWS")]
    public interface ActivoFijoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/insertarActivoFijoRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/insertarActivoFijoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ActivoFijoWS.insertarActivoFijoResponse insertarActivoFijo(TableSoft.ActivoFijoWS.insertarActivoFijoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/insertarActivoFijoRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/insertarActivoFijoResponse")]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.insertarActivoFijoResponse> insertarActivoFijoAsync(TableSoft.ActivoFijoWS.insertarActivoFijoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/actualizarActivoFijoRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/actualizarActivoFijoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ActivoFijoWS.actualizarActivoFijoResponse actualizarActivoFijo(TableSoft.ActivoFijoWS.actualizarActivoFijoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/actualizarActivoFijoRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/actualizarActivoFijoResponse")]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.actualizarActivoFijoResponse> actualizarActivoFijoAsync(TableSoft.ActivoFijoWS.actualizarActivoFijoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/listarActivosFijosRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/listarActivosFijosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ActivoFijoWS.listarActivosFijosResponse listarActivosFijos(TableSoft.ActivoFijoWS.listarActivosFijosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/listarActivosFijosRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/listarActivosFijosResponse")]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.listarActivosFijosResponse> listarActivosFijosAsync(TableSoft.ActivoFijoWS.listarActivosFijosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/listarActivosFijosPorNombreReq" +
            "uest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/listarActivosFijosPorNombreRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ActivoFijoWS.listarActivosFijosPorNombreResponse listarActivosFijosPorNombre(TableSoft.ActivoFijoWS.listarActivosFijosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/listarActivosFijosPorNombreReq" +
            "uest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/listarActivosFijosPorNombreRes" +
            "ponse")]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.listarActivosFijosPorNombreResponse> listarActivosFijosPorNombreAsync(TableSoft.ActivoFijoWS.listarActivosFijosPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/eliminarActivoFijoRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/eliminarActivoFijoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ActivoFijoWS.eliminarActivoFijoResponse eliminarActivoFijo(TableSoft.ActivoFijoWS.eliminarActivoFijoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/eliminarActivoFijoRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ActivoFijoWS/eliminarActivoFijoResponse")]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.eliminarActivoFijoResponse> eliminarActivoFijoAsync(TableSoft.ActivoFijoWS.eliminarActivoFijoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class activoFijo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int activoFijoIdField;
        
        private string codigoField;
        
        private string marcaField;
        
        private string nombreField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int activoFijoId {
            get {
                return this.activoFijoIdField;
            }
            set {
                this.activoFijoIdField = value;
                this.RaisePropertyChanged("activoFijoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarActivoFijo", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarActivoFijoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ActivoFijoWS.activoFijo objActivoFijo;
        
        public insertarActivoFijoRequest() {
        }
        
        public insertarActivoFijoRequest(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            this.objActivoFijo = objActivoFijo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarActivoFijoResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarActivoFijoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarActivoFijoResponse() {
        }
        
        public insertarActivoFijoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarActivoFijo", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarActivoFijoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ActivoFijoWS.activoFijo objActivoFijo;
        
        public actualizarActivoFijoRequest() {
        }
        
        public actualizarActivoFijoRequest(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            this.objActivoFijo = objActivoFijo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarActivoFijoResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarActivoFijoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarActivoFijoResponse() {
        }
        
        public actualizarActivoFijoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActivosFijos", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActivosFijosRequest {
        
        public listarActivosFijosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActivosFijosResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActivosFijosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ActivoFijoWS.activoFijo[] @return;
        
        public listarActivosFijosResponse() {
        }
        
        public listarActivosFijosResponse(TableSoft.ActivoFijoWS.activoFijo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActivosFijosPorNombre", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActivosFijosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarActivosFijosPorNombreRequest() {
        }
        
        public listarActivosFijosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActivosFijosPorNombreResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActivosFijosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ActivoFijoWS.activoFijo[] @return;
        
        public listarActivosFijosPorNombreResponse() {
        }
        
        public listarActivosFijosPorNombreResponse(TableSoft.ActivoFijoWS.activoFijo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarActivoFijo", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarActivoFijoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ActivoFijoWS.activoFijo objActivoFijo;
        
        public eliminarActivoFijoRequest() {
        }
        
        public eliminarActivoFijoRequest(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            this.objActivoFijo = objActivoFijo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarActivoFijoResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarActivoFijoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarActivoFijoResponse() {
        }
        
        public eliminarActivoFijoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActivoFijoWSChannel : TableSoft.ActivoFijoWS.ActivoFijoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivoFijoWSClient : System.ServiceModel.ClientBase<TableSoft.ActivoFijoWS.ActivoFijoWS>, TableSoft.ActivoFijoWS.ActivoFijoWS {
        
        public ActivoFijoWSClient() {
        }
        
        public ActivoFijoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivoFijoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivoFijoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivoFijoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ActivoFijoWS.insertarActivoFijoResponse TableSoft.ActivoFijoWS.ActivoFijoWS.insertarActivoFijo(TableSoft.ActivoFijoWS.insertarActivoFijoRequest request) {
            return base.Channel.insertarActivoFijo(request);
        }
        
        public int insertarActivoFijo(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            TableSoft.ActivoFijoWS.insertarActivoFijoRequest inValue = new TableSoft.ActivoFijoWS.insertarActivoFijoRequest();
            inValue.objActivoFijo = objActivoFijo;
            TableSoft.ActivoFijoWS.insertarActivoFijoResponse retVal = ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).insertarActivoFijo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.insertarActivoFijoResponse> TableSoft.ActivoFijoWS.ActivoFijoWS.insertarActivoFijoAsync(TableSoft.ActivoFijoWS.insertarActivoFijoRequest request) {
            return base.Channel.insertarActivoFijoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.insertarActivoFijoResponse> insertarActivoFijoAsync(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            TableSoft.ActivoFijoWS.insertarActivoFijoRequest inValue = new TableSoft.ActivoFijoWS.insertarActivoFijoRequest();
            inValue.objActivoFijo = objActivoFijo;
            return ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).insertarActivoFijoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ActivoFijoWS.actualizarActivoFijoResponse TableSoft.ActivoFijoWS.ActivoFijoWS.actualizarActivoFijo(TableSoft.ActivoFijoWS.actualizarActivoFijoRequest request) {
            return base.Channel.actualizarActivoFijo(request);
        }
        
        public int actualizarActivoFijo(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            TableSoft.ActivoFijoWS.actualizarActivoFijoRequest inValue = new TableSoft.ActivoFijoWS.actualizarActivoFijoRequest();
            inValue.objActivoFijo = objActivoFijo;
            TableSoft.ActivoFijoWS.actualizarActivoFijoResponse retVal = ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).actualizarActivoFijo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.actualizarActivoFijoResponse> TableSoft.ActivoFijoWS.ActivoFijoWS.actualizarActivoFijoAsync(TableSoft.ActivoFijoWS.actualizarActivoFijoRequest request) {
            return base.Channel.actualizarActivoFijoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.actualizarActivoFijoResponse> actualizarActivoFijoAsync(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            TableSoft.ActivoFijoWS.actualizarActivoFijoRequest inValue = new TableSoft.ActivoFijoWS.actualizarActivoFijoRequest();
            inValue.objActivoFijo = objActivoFijo;
            return ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).actualizarActivoFijoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ActivoFijoWS.listarActivosFijosResponse TableSoft.ActivoFijoWS.ActivoFijoWS.listarActivosFijos(TableSoft.ActivoFijoWS.listarActivosFijosRequest request) {
            return base.Channel.listarActivosFijos(request);
        }
        
        public TableSoft.ActivoFijoWS.activoFijo[] listarActivosFijos() {
            TableSoft.ActivoFijoWS.listarActivosFijosRequest inValue = new TableSoft.ActivoFijoWS.listarActivosFijosRequest();
            TableSoft.ActivoFijoWS.listarActivosFijosResponse retVal = ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).listarActivosFijos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.listarActivosFijosResponse> TableSoft.ActivoFijoWS.ActivoFijoWS.listarActivosFijosAsync(TableSoft.ActivoFijoWS.listarActivosFijosRequest request) {
            return base.Channel.listarActivosFijosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.listarActivosFijosResponse> listarActivosFijosAsync() {
            TableSoft.ActivoFijoWS.listarActivosFijosRequest inValue = new TableSoft.ActivoFijoWS.listarActivosFijosRequest();
            return ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).listarActivosFijosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ActivoFijoWS.listarActivosFijosPorNombreResponse TableSoft.ActivoFijoWS.ActivoFijoWS.listarActivosFijosPorNombre(TableSoft.ActivoFijoWS.listarActivosFijosPorNombreRequest request) {
            return base.Channel.listarActivosFijosPorNombre(request);
        }
        
        public TableSoft.ActivoFijoWS.activoFijo[] listarActivosFijosPorNombre(string nombre) {
            TableSoft.ActivoFijoWS.listarActivosFijosPorNombreRequest inValue = new TableSoft.ActivoFijoWS.listarActivosFijosPorNombreRequest();
            inValue.nombre = nombre;
            TableSoft.ActivoFijoWS.listarActivosFijosPorNombreResponse retVal = ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).listarActivosFijosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.listarActivosFijosPorNombreResponse> TableSoft.ActivoFijoWS.ActivoFijoWS.listarActivosFijosPorNombreAsync(TableSoft.ActivoFijoWS.listarActivosFijosPorNombreRequest request) {
            return base.Channel.listarActivosFijosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.listarActivosFijosPorNombreResponse> listarActivosFijosPorNombreAsync(string nombre) {
            TableSoft.ActivoFijoWS.listarActivosFijosPorNombreRequest inValue = new TableSoft.ActivoFijoWS.listarActivosFijosPorNombreRequest();
            inValue.nombre = nombre;
            return ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).listarActivosFijosPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ActivoFijoWS.eliminarActivoFijoResponse TableSoft.ActivoFijoWS.ActivoFijoWS.eliminarActivoFijo(TableSoft.ActivoFijoWS.eliminarActivoFijoRequest request) {
            return base.Channel.eliminarActivoFijo(request);
        }
        
        public int eliminarActivoFijo(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            TableSoft.ActivoFijoWS.eliminarActivoFijoRequest inValue = new TableSoft.ActivoFijoWS.eliminarActivoFijoRequest();
            inValue.objActivoFijo = objActivoFijo;
            TableSoft.ActivoFijoWS.eliminarActivoFijoResponse retVal = ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).eliminarActivoFijo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.eliminarActivoFijoResponse> TableSoft.ActivoFijoWS.ActivoFijoWS.eliminarActivoFijoAsync(TableSoft.ActivoFijoWS.eliminarActivoFijoRequest request) {
            return base.Channel.eliminarActivoFijoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ActivoFijoWS.eliminarActivoFijoResponse> eliminarActivoFijoAsync(TableSoft.ActivoFijoWS.activoFijo objActivoFijo) {
            TableSoft.ActivoFijoWS.eliminarActivoFijoRequest inValue = new TableSoft.ActivoFijoWS.eliminarActivoFijoRequest();
            inValue.objActivoFijo = objActivoFijo;
            return ((TableSoft.ActivoFijoWS.ActivoFijoWS)(this)).eliminarActivoFijoAsync(inValue);
        }
    }
}
