//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.PaisWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="PaisWS.PaisWS")]
    public interface PaisWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/PaisWS/listarPaisesRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/PaisWS/listarPaisesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.PaisWS.listarPaisesResponse listarPaises(TableSoft.PaisWS.listarPaisesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/PaisWS/listarPaisesRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/PaisWS/listarPaisesResponse")]
        System.Threading.Tasks.Task<TableSoft.PaisWS.listarPaisesResponse> listarPaisesAsync(TableSoft.PaisWS.listarPaisesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class pais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int paisIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int paisId {
            get {
                return this.paisIdField;
            }
            set {
                this.paisIdField = value;
                this.RaisePropertyChanged("paisId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPaises", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPaisesRequest {
        
        public listarPaisesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPaisesResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPaisesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.PaisWS.pais[] @return;
        
        public listarPaisesResponse() {
        }
        
        public listarPaisesResponse(TableSoft.PaisWS.pais[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaisWSChannel : TableSoft.PaisWS.PaisWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaisWSClient : System.ServiceModel.ClientBase<TableSoft.PaisWS.PaisWS>, TableSoft.PaisWS.PaisWS {
        
        public PaisWSClient() {
        }
        
        public PaisWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaisWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaisWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaisWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.PaisWS.listarPaisesResponse TableSoft.PaisWS.PaisWS.listarPaises(TableSoft.PaisWS.listarPaisesRequest request) {
            return base.Channel.listarPaises(request);
        }
        
        public TableSoft.PaisWS.pais[] listarPaises() {
            TableSoft.PaisWS.listarPaisesRequest inValue = new TableSoft.PaisWS.listarPaisesRequest();
            TableSoft.PaisWS.listarPaisesResponse retVal = ((TableSoft.PaisWS.PaisWS)(this)).listarPaises(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.PaisWS.listarPaisesResponse> TableSoft.PaisWS.PaisWS.listarPaisesAsync(TableSoft.PaisWS.listarPaisesRequest request) {
            return base.Channel.listarPaisesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.PaisWS.listarPaisesResponse> listarPaisesAsync() {
            TableSoft.PaisWS.listarPaisesRequest inValue = new TableSoft.PaisWS.listarPaisesRequest();
            return ((TableSoft.PaisWS.PaisWS)(this)).listarPaisesAsync(inValue);
        }
    }
}
