//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.UrgenciaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="UrgenciaWS.UrgenciaWS")]
    public interface UrgenciaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/insertarUrgenciaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/insertarUrgenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.UrgenciaWS.insertarUrgenciaResponse insertarUrgencia(TableSoft.UrgenciaWS.insertarUrgenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/insertarUrgenciaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/insertarUrgenciaResponse")]
        System.Threading.Tasks.Task<TableSoft.UrgenciaWS.insertarUrgenciaResponse> insertarUrgenciaAsync(TableSoft.UrgenciaWS.insertarUrgenciaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/eliminarUrgenciaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/eliminarUrgenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.UrgenciaWS.eliminarUrgenciaResponse eliminarUrgencia(TableSoft.UrgenciaWS.eliminarUrgenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/eliminarUrgenciaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/eliminarUrgenciaResponse")]
        System.Threading.Tasks.Task<TableSoft.UrgenciaWS.eliminarUrgenciaResponse> eliminarUrgenciaAsync(TableSoft.UrgenciaWS.eliminarUrgenciaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/listarUrgenciasRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/listarUrgenciasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.UrgenciaWS.listarUrgenciasResponse listarUrgencias(TableSoft.UrgenciaWS.listarUrgenciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/listarUrgenciasRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/listarUrgenciasResponse")]
        System.Threading.Tasks.Task<TableSoft.UrgenciaWS.listarUrgenciasResponse> listarUrgenciasAsync(TableSoft.UrgenciaWS.listarUrgenciasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/actualizarUrgenciaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/actualizarUrgenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.UrgenciaWS.actualizarUrgenciaResponse actualizarUrgencia(TableSoft.UrgenciaWS.actualizarUrgenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/actualizarUrgenciaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/UrgenciaWS/actualizarUrgenciaResponse")]
        System.Threading.Tasks.Task<TableSoft.UrgenciaWS.actualizarUrgenciaResponse> actualizarUrgenciaAsync(TableSoft.UrgenciaWS.actualizarUrgenciaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class urgencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string nombreField;
        
        private int plazoMaximoField;
        
        private int urgenciaIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int plazoMaximo {
            get {
                return this.plazoMaximoField;
            }
            set {
                this.plazoMaximoField = value;
                this.RaisePropertyChanged("plazoMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int urgenciaId {
            get {
                return this.urgenciaIdField;
            }
            set {
                this.urgenciaIdField = value;
                this.RaisePropertyChanged("urgenciaId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUrgencia", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUrgenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.UrgenciaWS.urgencia objUrgencia;
        
        public insertarUrgenciaRequest() {
        }
        
        public insertarUrgenciaRequest(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            this.objUrgencia = objUrgencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUrgenciaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUrgenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarUrgenciaResponse() {
        }
        
        public insertarUrgenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUrgencia", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUrgenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.UrgenciaWS.urgencia objUrgencia;
        
        public eliminarUrgenciaRequest() {
        }
        
        public eliminarUrgenciaRequest(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            this.objUrgencia = objUrgencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUrgenciaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUrgenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarUrgenciaResponse() {
        }
        
        public eliminarUrgenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUrgencias", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUrgenciasRequest {
        
        public listarUrgenciasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUrgenciasResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUrgenciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.UrgenciaWS.urgencia[] @return;
        
        public listarUrgenciasResponse() {
        }
        
        public listarUrgenciasResponse(TableSoft.UrgenciaWS.urgencia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarUrgencia", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarUrgenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.UrgenciaWS.urgencia objUrgencia;
        
        public actualizarUrgenciaRequest() {
        }
        
        public actualizarUrgenciaRequest(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            this.objUrgencia = objUrgencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarUrgenciaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarUrgenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarUrgenciaResponse() {
        }
        
        public actualizarUrgenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UrgenciaWSChannel : TableSoft.UrgenciaWS.UrgenciaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrgenciaWSClient : System.ServiceModel.ClientBase<TableSoft.UrgenciaWS.UrgenciaWS>, TableSoft.UrgenciaWS.UrgenciaWS {
        
        public UrgenciaWSClient() {
        }
        
        public UrgenciaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrgenciaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrgenciaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrgenciaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.UrgenciaWS.insertarUrgenciaResponse TableSoft.UrgenciaWS.UrgenciaWS.insertarUrgencia(TableSoft.UrgenciaWS.insertarUrgenciaRequest request) {
            return base.Channel.insertarUrgencia(request);
        }
        
        public int insertarUrgencia(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            TableSoft.UrgenciaWS.insertarUrgenciaRequest inValue = new TableSoft.UrgenciaWS.insertarUrgenciaRequest();
            inValue.objUrgencia = objUrgencia;
            TableSoft.UrgenciaWS.insertarUrgenciaResponse retVal = ((TableSoft.UrgenciaWS.UrgenciaWS)(this)).insertarUrgencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.UrgenciaWS.insertarUrgenciaResponse> TableSoft.UrgenciaWS.UrgenciaWS.insertarUrgenciaAsync(TableSoft.UrgenciaWS.insertarUrgenciaRequest request) {
            return base.Channel.insertarUrgenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.UrgenciaWS.insertarUrgenciaResponse> insertarUrgenciaAsync(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            TableSoft.UrgenciaWS.insertarUrgenciaRequest inValue = new TableSoft.UrgenciaWS.insertarUrgenciaRequest();
            inValue.objUrgencia = objUrgencia;
            return ((TableSoft.UrgenciaWS.UrgenciaWS)(this)).insertarUrgenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.UrgenciaWS.eliminarUrgenciaResponse TableSoft.UrgenciaWS.UrgenciaWS.eliminarUrgencia(TableSoft.UrgenciaWS.eliminarUrgenciaRequest request) {
            return base.Channel.eliminarUrgencia(request);
        }
        
        public int eliminarUrgencia(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            TableSoft.UrgenciaWS.eliminarUrgenciaRequest inValue = new TableSoft.UrgenciaWS.eliminarUrgenciaRequest();
            inValue.objUrgencia = objUrgencia;
            TableSoft.UrgenciaWS.eliminarUrgenciaResponse retVal = ((TableSoft.UrgenciaWS.UrgenciaWS)(this)).eliminarUrgencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.UrgenciaWS.eliminarUrgenciaResponse> TableSoft.UrgenciaWS.UrgenciaWS.eliminarUrgenciaAsync(TableSoft.UrgenciaWS.eliminarUrgenciaRequest request) {
            return base.Channel.eliminarUrgenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.UrgenciaWS.eliminarUrgenciaResponse> eliminarUrgenciaAsync(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            TableSoft.UrgenciaWS.eliminarUrgenciaRequest inValue = new TableSoft.UrgenciaWS.eliminarUrgenciaRequest();
            inValue.objUrgencia = objUrgencia;
            return ((TableSoft.UrgenciaWS.UrgenciaWS)(this)).eliminarUrgenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.UrgenciaWS.listarUrgenciasResponse TableSoft.UrgenciaWS.UrgenciaWS.listarUrgencias(TableSoft.UrgenciaWS.listarUrgenciasRequest request) {
            return base.Channel.listarUrgencias(request);
        }
        
        public TableSoft.UrgenciaWS.urgencia[] listarUrgencias() {
            TableSoft.UrgenciaWS.listarUrgenciasRequest inValue = new TableSoft.UrgenciaWS.listarUrgenciasRequest();
            TableSoft.UrgenciaWS.listarUrgenciasResponse retVal = ((TableSoft.UrgenciaWS.UrgenciaWS)(this)).listarUrgencias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.UrgenciaWS.listarUrgenciasResponse> TableSoft.UrgenciaWS.UrgenciaWS.listarUrgenciasAsync(TableSoft.UrgenciaWS.listarUrgenciasRequest request) {
            return base.Channel.listarUrgenciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.UrgenciaWS.listarUrgenciasResponse> listarUrgenciasAsync() {
            TableSoft.UrgenciaWS.listarUrgenciasRequest inValue = new TableSoft.UrgenciaWS.listarUrgenciasRequest();
            return ((TableSoft.UrgenciaWS.UrgenciaWS)(this)).listarUrgenciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.UrgenciaWS.actualizarUrgenciaResponse TableSoft.UrgenciaWS.UrgenciaWS.actualizarUrgencia(TableSoft.UrgenciaWS.actualizarUrgenciaRequest request) {
            return base.Channel.actualizarUrgencia(request);
        }
        
        public int actualizarUrgencia(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            TableSoft.UrgenciaWS.actualizarUrgenciaRequest inValue = new TableSoft.UrgenciaWS.actualizarUrgenciaRequest();
            inValue.objUrgencia = objUrgencia;
            TableSoft.UrgenciaWS.actualizarUrgenciaResponse retVal = ((TableSoft.UrgenciaWS.UrgenciaWS)(this)).actualizarUrgencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.UrgenciaWS.actualizarUrgenciaResponse> TableSoft.UrgenciaWS.UrgenciaWS.actualizarUrgenciaAsync(TableSoft.UrgenciaWS.actualizarUrgenciaRequest request) {
            return base.Channel.actualizarUrgenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.UrgenciaWS.actualizarUrgenciaResponse> actualizarUrgenciaAsync(TableSoft.UrgenciaWS.urgencia objUrgencia) {
            TableSoft.UrgenciaWS.actualizarUrgenciaRequest inValue = new TableSoft.UrgenciaWS.actualizarUrgenciaRequest();
            inValue.objUrgencia = objUrgencia;
            return ((TableSoft.UrgenciaWS.UrgenciaWS)(this)).actualizarUrgenciaAsync(inValue);
        }
    }
}
