//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.EmailWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pucp.edu.pe/", ConfigurationName="EmailWS.EmailWSSoap")]
    public interface EmailWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pucp.edu.pe/EnviarCorreo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EnviarCorreo(TableSoft.EmailWS.YanapayEmail email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pucp.edu.pe/EnviarCorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EnviarCorreoAsync(TableSoft.EmailWS.YanapayEmail email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pucp.edu.pe/EnviarCorreoString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EnviarCorreoString(string subject, string body, string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pucp.edu.pe/EnviarCorreoString", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EnviarCorreoStringAsync(string subject, string body, string recipient);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pucp.edu.pe/")]
    public partial class YanapayEmail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fromAddressField;
        
        private string toRecipientsField;
        
        private string subjectField;
        
        private string bodyField;
        
        private bool isHtmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FromAddress {
            get {
                return this.fromAddressField;
            }
            set {
                this.fromAddressField = value;
                this.RaisePropertyChanged("FromAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ToRecipients {
            get {
                return this.toRecipientsField;
            }
            set {
                this.toRecipientsField = value;
                this.RaisePropertyChanged("ToRecipients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsHtml {
            get {
                return this.isHtmlField;
            }
            set {
                this.isHtmlField = value;
                this.RaisePropertyChanged("IsHtml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmailWSSoapChannel : TableSoft.EmailWS.EmailWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailWSSoapClient : System.ServiceModel.ClientBase<TableSoft.EmailWS.EmailWSSoap>, TableSoft.EmailWS.EmailWSSoap {
        
        public EmailWSSoapClient() {
        }
        
        public EmailWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EnviarCorreo(TableSoft.EmailWS.YanapayEmail email) {
            return base.Channel.EnviarCorreo(email);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarCorreoAsync(TableSoft.EmailWS.YanapayEmail email) {
            return base.Channel.EnviarCorreoAsync(email);
        }
        
        public string EnviarCorreoString(string subject, string body, string recipient) {
            return base.Channel.EnviarCorreoString(subject, body, recipient);
        }
        
        public System.Threading.Tasks.Task<string> EnviarCorreoStringAsync(string subject, string body, string recipient) {
            return base.Channel.EnviarCorreoStringAsync(subject, body, recipient);
        }
    }
}
