//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.EstadoTicketWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="EstadoTicketWS.EstadoTicketWS")]
    public interface EstadoTicketWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/actualizarEstadoTicketReques" +
            "t", ReplyAction="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/actualizarEstadoTicketRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.EstadoTicketWS.actualizarEstadoTicketResponse actualizarEstadoTicket(TableSoft.EstadoTicketWS.actualizarEstadoTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/actualizarEstadoTicketReques" +
            "t", ReplyAction="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/actualizarEstadoTicketRespon" +
            "se")]
        System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.actualizarEstadoTicketResponse> actualizarEstadoTicketAsync(TableSoft.EstadoTicketWS.actualizarEstadoTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/listarEstadosTicketRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/listarEstadosTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.EstadoTicketWS.listarEstadosTicketResponse listarEstadosTicket(TableSoft.EstadoTicketWS.listarEstadosTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/listarEstadosTicketRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/listarEstadosTicketResponse")]
        System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.listarEstadosTicketResponse> listarEstadosTicketAsync(TableSoft.EstadoTicketWS.listarEstadosTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/insertarEstadoTicketRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/insertarEstadoTicketResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.EstadoTicketWS.insertarEstadoTicketResponse insertarEstadoTicket(TableSoft.EstadoTicketWS.insertarEstadoTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/insertarEstadoTicketRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/insertarEstadoTicketResponse" +
            "")]
        System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.insertarEstadoTicketResponse> insertarEstadoTicketAsync(TableSoft.EstadoTicketWS.insertarEstadoTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/eliminarEstadoTicketRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/eliminarEstadoTicketResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.EstadoTicketWS.eliminarEstadoTicketResponse eliminarEstadoTicket(TableSoft.EstadoTicketWS.eliminarEstadoTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/eliminarEstadoTicketRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/EstadoTicketWS/eliminarEstadoTicketResponse" +
            "")]
        System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.eliminarEstadoTicketResponse> eliminarEstadoTicketAsync(TableSoft.EstadoTicketWS.eliminarEstadoTicketRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class estadoTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int estadoIdField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int estadoId {
            get {
                return this.estadoIdField;
            }
            set {
                this.estadoIdField = value;
                this.RaisePropertyChanged("estadoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoTicket", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket;
        
        public actualizarEstadoTicketRequest() {
        }
        
        public actualizarEstadoTicketRequest(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            this.objEstadoTicket = objEstadoTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoTicketResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarEstadoTicketResponse() {
        }
        
        public actualizarEstadoTicketResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEstadosTicket", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEstadosTicketRequest {
        
        public listarEstadosTicketRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEstadosTicketResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEstadosTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.EstadoTicketWS.estadoTicket[] @return;
        
        public listarEstadosTicketResponse() {
        }
        
        public listarEstadosTicketResponse(TableSoft.EstadoTicketWS.estadoTicket[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEstadoTicket", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEstadoTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket;
        
        public insertarEstadoTicketRequest() {
        }
        
        public insertarEstadoTicketRequest(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            this.objEstadoTicket = objEstadoTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEstadoTicketResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEstadoTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEstadoTicketResponse() {
        }
        
        public insertarEstadoTicketResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEstadoTicket", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEstadoTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket;
        
        public eliminarEstadoTicketRequest() {
        }
        
        public eliminarEstadoTicketRequest(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            this.objEstadoTicket = objEstadoTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEstadoTicketResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEstadoTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEstadoTicketResponse() {
        }
        
        public eliminarEstadoTicketResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstadoTicketWSChannel : TableSoft.EstadoTicketWS.EstadoTicketWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoTicketWSClient : System.ServiceModel.ClientBase<TableSoft.EstadoTicketWS.EstadoTicketWS>, TableSoft.EstadoTicketWS.EstadoTicketWS {
        
        public EstadoTicketWSClient() {
        }
        
        public EstadoTicketWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadoTicketWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoTicketWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoTicketWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.EstadoTicketWS.actualizarEstadoTicketResponse TableSoft.EstadoTicketWS.EstadoTicketWS.actualizarEstadoTicket(TableSoft.EstadoTicketWS.actualizarEstadoTicketRequest request) {
            return base.Channel.actualizarEstadoTicket(request);
        }
        
        public int actualizarEstadoTicket(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            TableSoft.EstadoTicketWS.actualizarEstadoTicketRequest inValue = new TableSoft.EstadoTicketWS.actualizarEstadoTicketRequest();
            inValue.objEstadoTicket = objEstadoTicket;
            TableSoft.EstadoTicketWS.actualizarEstadoTicketResponse retVal = ((TableSoft.EstadoTicketWS.EstadoTicketWS)(this)).actualizarEstadoTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.actualizarEstadoTicketResponse> TableSoft.EstadoTicketWS.EstadoTicketWS.actualizarEstadoTicketAsync(TableSoft.EstadoTicketWS.actualizarEstadoTicketRequest request) {
            return base.Channel.actualizarEstadoTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.actualizarEstadoTicketResponse> actualizarEstadoTicketAsync(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            TableSoft.EstadoTicketWS.actualizarEstadoTicketRequest inValue = new TableSoft.EstadoTicketWS.actualizarEstadoTicketRequest();
            inValue.objEstadoTicket = objEstadoTicket;
            return ((TableSoft.EstadoTicketWS.EstadoTicketWS)(this)).actualizarEstadoTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.EstadoTicketWS.listarEstadosTicketResponse TableSoft.EstadoTicketWS.EstadoTicketWS.listarEstadosTicket(TableSoft.EstadoTicketWS.listarEstadosTicketRequest request) {
            return base.Channel.listarEstadosTicket(request);
        }
        
        public TableSoft.EstadoTicketWS.estadoTicket[] listarEstadosTicket() {
            TableSoft.EstadoTicketWS.listarEstadosTicketRequest inValue = new TableSoft.EstadoTicketWS.listarEstadosTicketRequest();
            TableSoft.EstadoTicketWS.listarEstadosTicketResponse retVal = ((TableSoft.EstadoTicketWS.EstadoTicketWS)(this)).listarEstadosTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.listarEstadosTicketResponse> TableSoft.EstadoTicketWS.EstadoTicketWS.listarEstadosTicketAsync(TableSoft.EstadoTicketWS.listarEstadosTicketRequest request) {
            return base.Channel.listarEstadosTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.listarEstadosTicketResponse> listarEstadosTicketAsync() {
            TableSoft.EstadoTicketWS.listarEstadosTicketRequest inValue = new TableSoft.EstadoTicketWS.listarEstadosTicketRequest();
            return ((TableSoft.EstadoTicketWS.EstadoTicketWS)(this)).listarEstadosTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.EstadoTicketWS.insertarEstadoTicketResponse TableSoft.EstadoTicketWS.EstadoTicketWS.insertarEstadoTicket(TableSoft.EstadoTicketWS.insertarEstadoTicketRequest request) {
            return base.Channel.insertarEstadoTicket(request);
        }
        
        public int insertarEstadoTicket(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            TableSoft.EstadoTicketWS.insertarEstadoTicketRequest inValue = new TableSoft.EstadoTicketWS.insertarEstadoTicketRequest();
            inValue.objEstadoTicket = objEstadoTicket;
            TableSoft.EstadoTicketWS.insertarEstadoTicketResponse retVal = ((TableSoft.EstadoTicketWS.EstadoTicketWS)(this)).insertarEstadoTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.insertarEstadoTicketResponse> TableSoft.EstadoTicketWS.EstadoTicketWS.insertarEstadoTicketAsync(TableSoft.EstadoTicketWS.insertarEstadoTicketRequest request) {
            return base.Channel.insertarEstadoTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.insertarEstadoTicketResponse> insertarEstadoTicketAsync(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            TableSoft.EstadoTicketWS.insertarEstadoTicketRequest inValue = new TableSoft.EstadoTicketWS.insertarEstadoTicketRequest();
            inValue.objEstadoTicket = objEstadoTicket;
            return ((TableSoft.EstadoTicketWS.EstadoTicketWS)(this)).insertarEstadoTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.EstadoTicketWS.eliminarEstadoTicketResponse TableSoft.EstadoTicketWS.EstadoTicketWS.eliminarEstadoTicket(TableSoft.EstadoTicketWS.eliminarEstadoTicketRequest request) {
            return base.Channel.eliminarEstadoTicket(request);
        }
        
        public int eliminarEstadoTicket(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            TableSoft.EstadoTicketWS.eliminarEstadoTicketRequest inValue = new TableSoft.EstadoTicketWS.eliminarEstadoTicketRequest();
            inValue.objEstadoTicket = objEstadoTicket;
            TableSoft.EstadoTicketWS.eliminarEstadoTicketResponse retVal = ((TableSoft.EstadoTicketWS.EstadoTicketWS)(this)).eliminarEstadoTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.eliminarEstadoTicketResponse> TableSoft.EstadoTicketWS.EstadoTicketWS.eliminarEstadoTicketAsync(TableSoft.EstadoTicketWS.eliminarEstadoTicketRequest request) {
            return base.Channel.eliminarEstadoTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.EstadoTicketWS.eliminarEstadoTicketResponse> eliminarEstadoTicketAsync(TableSoft.EstadoTicketWS.estadoTicket objEstadoTicket) {
            TableSoft.EstadoTicketWS.eliminarEstadoTicketRequest inValue = new TableSoft.EstadoTicketWS.eliminarEstadoTicketRequest();
            inValue.objEstadoTicket = objEstadoTicket;
            return ((TableSoft.EstadoTicketWS.EstadoTicketWS)(this)).eliminarEstadoTicketAsync(inValue);
        }
    }
}
