//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.RolWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="RolWS.RolWS")]
    public interface RolWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/RolWS/insertarRolRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/RolWS/insertarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.RolWS.insertarRolResponse insertarRol(TableSoft.RolWS.insertarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/RolWS/insertarRolRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/RolWS/insertarRolResponse")]
        System.Threading.Tasks.Task<TableSoft.RolWS.insertarRolResponse> insertarRolAsync(TableSoft.RolWS.insertarRolRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/RolWS/listarRolesRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/RolWS/listarRolesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.RolWS.listarRolesResponse listarRoles(TableSoft.RolWS.listarRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/RolWS/listarRolesRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/RolWS/listarRolesResponse")]
        System.Threading.Tasks.Task<TableSoft.RolWS.listarRolesResponse> listarRolesAsync(TableSoft.RolWS.listarRolesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/RolWS/eliminarRolRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/RolWS/eliminarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.RolWS.eliminarRolResponse eliminarRol(TableSoft.RolWS.eliminarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/RolWS/eliminarRolRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/RolWS/eliminarRolResponse")]
        System.Threading.Tasks.Task<TableSoft.RolWS.eliminarRolResponse> eliminarRolAsync(TableSoft.RolWS.eliminarRolRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/RolWS/actualizarRolRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/RolWS/actualizarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.RolWS.actualizarRolResponse actualizarRol(TableSoft.RolWS.actualizarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/RolWS/actualizarRolRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/RolWS/actualizarRolResponse")]
        System.Threading.Tasks.Task<TableSoft.RolWS.actualizarRolResponse> actualizarRolAsync(TableSoft.RolWS.actualizarRolRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string descripcionField;
        
        private string nombreField;
        
        private int rolIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int rolId {
            get {
                return this.rolIdField;
            }
            set {
                this.rolIdField = value;
                this.RaisePropertyChanged("rolId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRol", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.RolWS.rol objRol;
        
        public insertarRolRequest() {
        }
        
        public insertarRolRequest(TableSoft.RolWS.rol objRol) {
            this.objRol = objRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRolResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarRolResponse() {
        }
        
        public insertarRolResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRoles", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.RolWS.rol objRol;
        
        public listarRolesRequest() {
        }
        
        public listarRolesRequest(TableSoft.RolWS.rol objRol) {
            this.objRol = objRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRolesResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.RolWS.rol[] @return;
        
        public listarRolesResponse() {
        }
        
        public listarRolesResponse(TableSoft.RolWS.rol[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRol", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.RolWS.rol objRol;
        
        public eliminarRolRequest() {
        }
        
        public eliminarRolRequest(TableSoft.RolWS.rol objRol) {
            this.objRol = objRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRolResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarRolResponse() {
        }
        
        public eliminarRolResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarRol", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.RolWS.rol objRol;
        
        public actualizarRolRequest() {
        }
        
        public actualizarRolRequest(TableSoft.RolWS.rol objRol) {
            this.objRol = objRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarRolResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarRolResponse() {
        }
        
        public actualizarRolResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RolWSChannel : TableSoft.RolWS.RolWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RolWSClient : System.ServiceModel.ClientBase<TableSoft.RolWS.RolWS>, TableSoft.RolWS.RolWS {
        
        public RolWSClient() {
        }
        
        public RolWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RolWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.RolWS.insertarRolResponse TableSoft.RolWS.RolWS.insertarRol(TableSoft.RolWS.insertarRolRequest request) {
            return base.Channel.insertarRol(request);
        }
        
        public int insertarRol(TableSoft.RolWS.rol objRol) {
            TableSoft.RolWS.insertarRolRequest inValue = new TableSoft.RolWS.insertarRolRequest();
            inValue.objRol = objRol;
            TableSoft.RolWS.insertarRolResponse retVal = ((TableSoft.RolWS.RolWS)(this)).insertarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.RolWS.insertarRolResponse> TableSoft.RolWS.RolWS.insertarRolAsync(TableSoft.RolWS.insertarRolRequest request) {
            return base.Channel.insertarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.RolWS.insertarRolResponse> insertarRolAsync(TableSoft.RolWS.rol objRol) {
            TableSoft.RolWS.insertarRolRequest inValue = new TableSoft.RolWS.insertarRolRequest();
            inValue.objRol = objRol;
            return ((TableSoft.RolWS.RolWS)(this)).insertarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.RolWS.listarRolesResponse TableSoft.RolWS.RolWS.listarRoles(TableSoft.RolWS.listarRolesRequest request) {
            return base.Channel.listarRoles(request);
        }
        
        public TableSoft.RolWS.rol[] listarRoles(TableSoft.RolWS.rol objRol) {
            TableSoft.RolWS.listarRolesRequest inValue = new TableSoft.RolWS.listarRolesRequest();
            inValue.objRol = objRol;
            TableSoft.RolWS.listarRolesResponse retVal = ((TableSoft.RolWS.RolWS)(this)).listarRoles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.RolWS.listarRolesResponse> TableSoft.RolWS.RolWS.listarRolesAsync(TableSoft.RolWS.listarRolesRequest request) {
            return base.Channel.listarRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.RolWS.listarRolesResponse> listarRolesAsync(TableSoft.RolWS.rol objRol) {
            TableSoft.RolWS.listarRolesRequest inValue = new TableSoft.RolWS.listarRolesRequest();
            inValue.objRol = objRol;
            return ((TableSoft.RolWS.RolWS)(this)).listarRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.RolWS.eliminarRolResponse TableSoft.RolWS.RolWS.eliminarRol(TableSoft.RolWS.eliminarRolRequest request) {
            return base.Channel.eliminarRol(request);
        }
        
        public int eliminarRol(TableSoft.RolWS.rol objRol) {
            TableSoft.RolWS.eliminarRolRequest inValue = new TableSoft.RolWS.eliminarRolRequest();
            inValue.objRol = objRol;
            TableSoft.RolWS.eliminarRolResponse retVal = ((TableSoft.RolWS.RolWS)(this)).eliminarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.RolWS.eliminarRolResponse> TableSoft.RolWS.RolWS.eliminarRolAsync(TableSoft.RolWS.eliminarRolRequest request) {
            return base.Channel.eliminarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.RolWS.eliminarRolResponse> eliminarRolAsync(TableSoft.RolWS.rol objRol) {
            TableSoft.RolWS.eliminarRolRequest inValue = new TableSoft.RolWS.eliminarRolRequest();
            inValue.objRol = objRol;
            return ((TableSoft.RolWS.RolWS)(this)).eliminarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.RolWS.actualizarRolResponse TableSoft.RolWS.RolWS.actualizarRol(TableSoft.RolWS.actualizarRolRequest request) {
            return base.Channel.actualizarRol(request);
        }
        
        public int actualizarRol(TableSoft.RolWS.rol objRol) {
            TableSoft.RolWS.actualizarRolRequest inValue = new TableSoft.RolWS.actualizarRolRequest();
            inValue.objRol = objRol;
            TableSoft.RolWS.actualizarRolResponse retVal = ((TableSoft.RolWS.RolWS)(this)).actualizarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.RolWS.actualizarRolResponse> TableSoft.RolWS.RolWS.actualizarRolAsync(TableSoft.RolWS.actualizarRolRequest request) {
            return base.Channel.actualizarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.RolWS.actualizarRolResponse> actualizarRolAsync(TableSoft.RolWS.rol objRol) {
            TableSoft.RolWS.actualizarRolRequest inValue = new TableSoft.RolWS.actualizarRolRequest();
            inValue.objRol = objRol;
            return ((TableSoft.RolWS.RolWS)(this)).actualizarRolAsync(inValue);
        }
    }
}
