//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.ProveedorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="ProveedorWS.ProveedorWS")]
    public interface ProveedorWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/actualizarProveedorRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/actualizarProveedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ProveedorWS.actualizarProveedorResponse actualizarProveedor(TableSoft.ProveedorWS.actualizarProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/actualizarProveedorRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/actualizarProveedorResponse")]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.actualizarProveedorResponse> actualizarProveedorAsync(TableSoft.ProveedorWS.actualizarProveedorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/listarProveedoresRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/listarProveedoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ProveedorWS.listarProveedoresResponse listarProveedores(TableSoft.ProveedorWS.listarProveedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/listarProveedoresRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/listarProveedoresResponse")]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.listarProveedoresResponse> listarProveedoresAsync(TableSoft.ProveedorWS.listarProveedoresRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/eliminarProveedorRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/eliminarProveedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ProveedorWS.eliminarProveedorResponse eliminarProveedor(TableSoft.ProveedorWS.eliminarProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/eliminarProveedorRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/eliminarProveedorResponse")]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.eliminarProveedorResponse> eliminarProveedorAsync(TableSoft.ProveedorWS.eliminarProveedorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/insertarProveedorRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/insertarProveedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ProveedorWS.insertarProveedorResponse insertarProveedor(TableSoft.ProveedorWS.insertarProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/insertarProveedorRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/insertarProveedorResponse")]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.insertarProveedorResponse> insertarProveedorAsync(TableSoft.ProveedorWS.insertarProveedorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/listarProveedoresPorNombreReque" +
            "st", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/listarProveedoresPorNombreRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ProveedorWS.listarProveedoresPorNombreResponse listarProveedoresPorNombre(TableSoft.ProveedorWS.listarProveedoresPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ProveedorWS/listarProveedoresPorNombreReque" +
            "st", ReplyAction="http://services.tablesoft.pucp.edu.pe/ProveedorWS/listarProveedoresPorNombreRespo" +
            "nse")]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.listarProveedoresPorNombreResponse> listarProveedoresPorNombreAsync(TableSoft.ProveedorWS.listarProveedoresPorNombreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class proveedor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private ciudad ciudadField;
        
        private string direccionField;
        
        private string emailField;
        
        private int proveedorIdField;
        
        private string razonSocialField;
        
        private string rucField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ciudad ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int proveedorId {
            get {
                return this.proveedorIdField;
            }
            set {
                this.proveedorIdField = value;
                this.RaisePropertyChanged("proveedorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class ciudad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ciudadIdField;
        
        private string nombreField;
        
        private pais paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ciudadId {
            get {
                return this.ciudadIdField;
            }
            set {
                this.ciudadIdField = value;
                this.RaisePropertyChanged("ciudadId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public pais pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class pais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int paisIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int paisId {
            get {
                return this.paisIdField;
            }
            set {
                this.paisIdField = value;
                this.RaisePropertyChanged("paisId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarProveedor", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ProveedorWS.proveedor objProveedor;
        
        public actualizarProveedorRequest() {
        }
        
        public actualizarProveedorRequest(TableSoft.ProveedorWS.proveedor objProveedor) {
            this.objProveedor = objProveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarProveedorResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarProveedorResponse() {
        }
        
        public actualizarProveedorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProveedores", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProveedoresRequest {
        
        public listarProveedoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProveedoresResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ProveedorWS.proveedor[] @return;
        
        public listarProveedoresResponse() {
        }
        
        public listarProveedoresResponse(TableSoft.ProveedorWS.proveedor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProveedor", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ProveedorWS.proveedor objProveedor;
        
        public eliminarProveedorRequest() {
        }
        
        public eliminarProveedorRequest(TableSoft.ProveedorWS.proveedor objProveedor) {
            this.objProveedor = objProveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProveedorResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarProveedorResponse() {
        }
        
        public eliminarProveedorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProveedor", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ProveedorWS.proveedor objProveedor;
        
        public insertarProveedorRequest() {
        }
        
        public insertarProveedorRequest(TableSoft.ProveedorWS.proveedor objProveedor) {
            this.objProveedor = objProveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProveedorResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarProveedorResponse() {
        }
        
        public insertarProveedorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProveedoresPorNombre", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProveedoresPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarProveedoresPorNombreRequest() {
        }
        
        public listarProveedoresPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProveedoresPorNombreResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProveedoresPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ProveedorWS.proveedor[] @return;
        
        public listarProveedoresPorNombreResponse() {
        }
        
        public listarProveedoresPorNombreResponse(TableSoft.ProveedorWS.proveedor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProveedorWSChannel : TableSoft.ProveedorWS.ProveedorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProveedorWSClient : System.ServiceModel.ClientBase<TableSoft.ProveedorWS.ProveedorWS>, TableSoft.ProveedorWS.ProveedorWS {
        
        public ProveedorWSClient() {
        }
        
        public ProveedorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProveedorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ProveedorWS.actualizarProveedorResponse TableSoft.ProveedorWS.ProveedorWS.actualizarProveedor(TableSoft.ProveedorWS.actualizarProveedorRequest request) {
            return base.Channel.actualizarProveedor(request);
        }
        
        public int actualizarProveedor(TableSoft.ProveedorWS.proveedor objProveedor) {
            TableSoft.ProveedorWS.actualizarProveedorRequest inValue = new TableSoft.ProveedorWS.actualizarProveedorRequest();
            inValue.objProveedor = objProveedor;
            TableSoft.ProveedorWS.actualizarProveedorResponse retVal = ((TableSoft.ProveedorWS.ProveedorWS)(this)).actualizarProveedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.actualizarProveedorResponse> TableSoft.ProveedorWS.ProveedorWS.actualizarProveedorAsync(TableSoft.ProveedorWS.actualizarProveedorRequest request) {
            return base.Channel.actualizarProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ProveedorWS.actualizarProveedorResponse> actualizarProveedorAsync(TableSoft.ProveedorWS.proveedor objProveedor) {
            TableSoft.ProveedorWS.actualizarProveedorRequest inValue = new TableSoft.ProveedorWS.actualizarProveedorRequest();
            inValue.objProveedor = objProveedor;
            return ((TableSoft.ProveedorWS.ProveedorWS)(this)).actualizarProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ProveedorWS.listarProveedoresResponse TableSoft.ProveedorWS.ProveedorWS.listarProveedores(TableSoft.ProveedorWS.listarProveedoresRequest request) {
            return base.Channel.listarProveedores(request);
        }
        
        public TableSoft.ProveedorWS.proveedor[] listarProveedores() {
            TableSoft.ProveedorWS.listarProveedoresRequest inValue = new TableSoft.ProveedorWS.listarProveedoresRequest();
            TableSoft.ProveedorWS.listarProveedoresResponse retVal = ((TableSoft.ProveedorWS.ProveedorWS)(this)).listarProveedores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.listarProveedoresResponse> TableSoft.ProveedorWS.ProveedorWS.listarProveedoresAsync(TableSoft.ProveedorWS.listarProveedoresRequest request) {
            return base.Channel.listarProveedoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ProveedorWS.listarProveedoresResponse> listarProveedoresAsync() {
            TableSoft.ProveedorWS.listarProveedoresRequest inValue = new TableSoft.ProveedorWS.listarProveedoresRequest();
            return ((TableSoft.ProveedorWS.ProveedorWS)(this)).listarProveedoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ProveedorWS.eliminarProveedorResponse TableSoft.ProveedorWS.ProveedorWS.eliminarProveedor(TableSoft.ProveedorWS.eliminarProveedorRequest request) {
            return base.Channel.eliminarProveedor(request);
        }
        
        public int eliminarProveedor(TableSoft.ProveedorWS.proveedor objProveedor) {
            TableSoft.ProveedorWS.eliminarProveedorRequest inValue = new TableSoft.ProveedorWS.eliminarProveedorRequest();
            inValue.objProveedor = objProveedor;
            TableSoft.ProveedorWS.eliminarProveedorResponse retVal = ((TableSoft.ProveedorWS.ProveedorWS)(this)).eliminarProveedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.eliminarProveedorResponse> TableSoft.ProveedorWS.ProveedorWS.eliminarProveedorAsync(TableSoft.ProveedorWS.eliminarProveedorRequest request) {
            return base.Channel.eliminarProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ProveedorWS.eliminarProveedorResponse> eliminarProveedorAsync(TableSoft.ProveedorWS.proveedor objProveedor) {
            TableSoft.ProveedorWS.eliminarProveedorRequest inValue = new TableSoft.ProveedorWS.eliminarProveedorRequest();
            inValue.objProveedor = objProveedor;
            return ((TableSoft.ProveedorWS.ProveedorWS)(this)).eliminarProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ProveedorWS.insertarProveedorResponse TableSoft.ProveedorWS.ProveedorWS.insertarProveedor(TableSoft.ProveedorWS.insertarProveedorRequest request) {
            return base.Channel.insertarProveedor(request);
        }
        
        public int insertarProveedor(TableSoft.ProveedorWS.proveedor objProveedor) {
            TableSoft.ProveedorWS.insertarProveedorRequest inValue = new TableSoft.ProveedorWS.insertarProveedorRequest();
            inValue.objProveedor = objProveedor;
            TableSoft.ProveedorWS.insertarProveedorResponse retVal = ((TableSoft.ProveedorWS.ProveedorWS)(this)).insertarProveedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.insertarProveedorResponse> TableSoft.ProveedorWS.ProveedorWS.insertarProveedorAsync(TableSoft.ProveedorWS.insertarProveedorRequest request) {
            return base.Channel.insertarProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ProveedorWS.insertarProveedorResponse> insertarProveedorAsync(TableSoft.ProveedorWS.proveedor objProveedor) {
            TableSoft.ProveedorWS.insertarProveedorRequest inValue = new TableSoft.ProveedorWS.insertarProveedorRequest();
            inValue.objProveedor = objProveedor;
            return ((TableSoft.ProveedorWS.ProveedorWS)(this)).insertarProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ProveedorWS.listarProveedoresPorNombreResponse TableSoft.ProveedorWS.ProveedorWS.listarProveedoresPorNombre(TableSoft.ProveedorWS.listarProveedoresPorNombreRequest request) {
            return base.Channel.listarProveedoresPorNombre(request);
        }
        
        public TableSoft.ProveedorWS.proveedor[] listarProveedoresPorNombre(string nombre) {
            TableSoft.ProveedorWS.listarProveedoresPorNombreRequest inValue = new TableSoft.ProveedorWS.listarProveedoresPorNombreRequest();
            inValue.nombre = nombre;
            TableSoft.ProveedorWS.listarProveedoresPorNombreResponse retVal = ((TableSoft.ProveedorWS.ProveedorWS)(this)).listarProveedoresPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ProveedorWS.listarProveedoresPorNombreResponse> TableSoft.ProveedorWS.ProveedorWS.listarProveedoresPorNombreAsync(TableSoft.ProveedorWS.listarProveedoresPorNombreRequest request) {
            return base.Channel.listarProveedoresPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ProveedorWS.listarProveedoresPorNombreResponse> listarProveedoresPorNombreAsync(string nombre) {
            TableSoft.ProveedorWS.listarProveedoresPorNombreRequest inValue = new TableSoft.ProveedorWS.listarProveedoresPorNombreRequest();
            inValue.nombre = nombre;
            return ((TableSoft.ProveedorWS.ProveedorWS)(this)).listarProveedoresPorNombreAsync(inValue);
        }
    }
}
