//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.CiudadWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="CiudadWS.CiudadWS")]
    public interface CiudadWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/CiudadWS/listarCiudadesDePaisRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/CiudadWS/listarCiudadesDePaisResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.CiudadWS.listarCiudadesDePaisResponse listarCiudadesDePais(TableSoft.CiudadWS.listarCiudadesDePaisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/CiudadWS/listarCiudadesDePaisRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/CiudadWS/listarCiudadesDePaisResponse")]
        System.Threading.Tasks.Task<TableSoft.CiudadWS.listarCiudadesDePaisResponse> listarCiudadesDePaisAsync(TableSoft.CiudadWS.listarCiudadesDePaisRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class pais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int paisIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int paisId {
            get {
                return this.paisIdField;
            }
            set {
                this.paisIdField = value;
                this.RaisePropertyChanged("paisId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class ciudad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ciudadIdField;
        
        private string nombreField;
        
        private pais paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ciudadId {
            get {
                return this.ciudadIdField;
            }
            set {
                this.ciudadIdField = value;
                this.RaisePropertyChanged("ciudadId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public pais pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCiudadesDePais", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCiudadesDePaisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.CiudadWS.pais objPais;
        
        public listarCiudadesDePaisRequest() {
        }
        
        public listarCiudadesDePaisRequest(TableSoft.CiudadWS.pais objPais) {
            this.objPais = objPais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCiudadesDePaisResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCiudadesDePaisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.CiudadWS.ciudad[] @return;
        
        public listarCiudadesDePaisResponse() {
        }
        
        public listarCiudadesDePaisResponse(TableSoft.CiudadWS.ciudad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CiudadWSChannel : TableSoft.CiudadWS.CiudadWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CiudadWSClient : System.ServiceModel.ClientBase<TableSoft.CiudadWS.CiudadWS>, TableSoft.CiudadWS.CiudadWS {
        
        public CiudadWSClient() {
        }
        
        public CiudadWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CiudadWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CiudadWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CiudadWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.CiudadWS.listarCiudadesDePaisResponse TableSoft.CiudadWS.CiudadWS.listarCiudadesDePais(TableSoft.CiudadWS.listarCiudadesDePaisRequest request) {
            return base.Channel.listarCiudadesDePais(request);
        }
        
        public TableSoft.CiudadWS.ciudad[] listarCiudadesDePais(TableSoft.CiudadWS.pais objPais) {
            TableSoft.CiudadWS.listarCiudadesDePaisRequest inValue = new TableSoft.CiudadWS.listarCiudadesDePaisRequest();
            inValue.objPais = objPais;
            TableSoft.CiudadWS.listarCiudadesDePaisResponse retVal = ((TableSoft.CiudadWS.CiudadWS)(this)).listarCiudadesDePais(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.CiudadWS.listarCiudadesDePaisResponse> TableSoft.CiudadWS.CiudadWS.listarCiudadesDePaisAsync(TableSoft.CiudadWS.listarCiudadesDePaisRequest request) {
            return base.Channel.listarCiudadesDePaisAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.CiudadWS.listarCiudadesDePaisResponse> listarCiudadesDePaisAsync(TableSoft.CiudadWS.pais objPais) {
            TableSoft.CiudadWS.listarCiudadesDePaisRequest inValue = new TableSoft.CiudadWS.listarCiudadesDePaisRequest();
            inValue.objPais = objPais;
            return ((TableSoft.CiudadWS.CiudadWS)(this)).listarCiudadesDePaisAsync(inValue);
        }
    }
}
