//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.ReporteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="ReporteWS.ReporteWS")]
    public interface ReporteWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ReporteWS.generarReporteTicketResponse generarReporteTicket(TableSoft.ReporteWS.generarReporteTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketResponse")]
        System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketResponse> generarReporteTicketAsync(TableSoft.ReporteWS.generarReporteTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketUrgenciaReque" +
            "st", ReplyAction="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketUrgenciaRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ReporteWS.generarReporteTicketUrgenciaResponse generarReporteTicketUrgencia(TableSoft.ReporteWS.generarReporteTicketUrgenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketUrgenciaReque" +
            "st", ReplyAction="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketUrgenciaRespo" +
            "nse")]
        System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketUrgenciaResponse> generarReporteTicketUrgenciaAsync(TableSoft.ReporteWS.generarReporteTicketUrgenciaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketCategoriaRequ" +
            "est", ReplyAction="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketCategoriaResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.ReporteWS.generarReporteTicketCategoriaResponse generarReporteTicketCategoria(TableSoft.ReporteWS.generarReporteTicketCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketCategoriaRequ" +
            "est", ReplyAction="http://services.tablesoft.pucp.edu.pe/ReporteWS/generarReporteTicketCategoriaResp" +
            "onse")]
        System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketCategoriaResponse> generarReporteTicketCategoriaAsync(TableSoft.ReporteWS.generarReporteTicketCategoriaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteTicket", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTicket;
        
        public generarReporteTicketRequest() {
        }
        
        public generarReporteTicketRequest(int idTicket) {
            this.idTicket = idTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteTicketResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generarReporteTicketResponse() {
        }
        
        public generarReporteTicketResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class urgencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string nombreField;
        
        private int plazoMaximoField;
        
        private int urgenciaIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int plazoMaximo {
            get {
                return this.plazoMaximoField;
            }
            set {
                this.plazoMaximoField = value;
                this.RaisePropertyChanged("plazoMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int urgenciaId {
            get {
                return this.urgenciaIdField;
            }
            set {
                this.urgenciaIdField = value;
                this.RaisePropertyChanged("urgenciaId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class tareaPredeterminada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private string fechaCreacionField;
        
        private int tareaPredeterminadaIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tareaPredeterminadaId {
            get {
                return this.tareaPredeterminadaIdField;
            }
            set {
                this.tareaPredeterminadaIdField = value;
                this.RaisePropertyChanged("tareaPredeterminadaId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int categoriaIdField;
        
        private string descripcionField;
        
        private string nombreField;
        
        private tareaPredeterminada[] tareasPredeterminadasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int categoriaId {
            get {
                return this.categoriaIdField;
            }
            set {
                this.categoriaIdField = value;
                this.RaisePropertyChanged("categoriaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tareasPredeterminadas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public tareaPredeterminada[] tareasPredeterminadas {
            get {
                return this.tareasPredeterminadasField;
            }
            set {
                this.tareasPredeterminadasField = value;
                this.RaisePropertyChanged("tareasPredeterminadas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteTicketUrgencia", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteTicketUrgenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ReporteWS.urgencia objUrgencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin;
        
        public generarReporteTicketUrgenciaRequest() {
        }
        
        public generarReporteTicketUrgenciaRequest(TableSoft.ReporteWS.urgencia objUrgencia, System.DateTime fechaIni, System.DateTime fechaFin) {
            this.objUrgencia = objUrgencia;
            this.fechaIni = fechaIni;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteTicketUrgenciaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteTicketUrgenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generarReporteTicketUrgenciaResponse() {
        }
        
        public generarReporteTicketUrgenciaResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteTicketCategoria", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteTicketCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.ReporteWS.categoria objCategoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin;
        
        public generarReporteTicketCategoriaRequest() {
        }
        
        public generarReporteTicketCategoriaRequest(TableSoft.ReporteWS.categoria objCategoria, System.DateTime fechaIni, System.DateTime fechaFin) {
            this.objCategoria = objCategoria;
            this.fechaIni = fechaIni;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteTicketCategoriaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteTicketCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generarReporteTicketCategoriaResponse() {
        }
        
        public generarReporteTicketCategoriaResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteWSChannel : TableSoft.ReporteWS.ReporteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteWSClient : System.ServiceModel.ClientBase<TableSoft.ReporteWS.ReporteWS>, TableSoft.ReporteWS.ReporteWS {
        
        public ReporteWSClient() {
        }
        
        public ReporteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ReporteWS.generarReporteTicketResponse TableSoft.ReporteWS.ReporteWS.generarReporteTicket(TableSoft.ReporteWS.generarReporteTicketRequest request) {
            return base.Channel.generarReporteTicket(request);
        }
        
        public byte[] generarReporteTicket(int idTicket) {
            TableSoft.ReporteWS.generarReporteTicketRequest inValue = new TableSoft.ReporteWS.generarReporteTicketRequest();
            inValue.idTicket = idTicket;
            TableSoft.ReporteWS.generarReporteTicketResponse retVal = ((TableSoft.ReporteWS.ReporteWS)(this)).generarReporteTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketResponse> TableSoft.ReporteWS.ReporteWS.generarReporteTicketAsync(TableSoft.ReporteWS.generarReporteTicketRequest request) {
            return base.Channel.generarReporteTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketResponse> generarReporteTicketAsync(int idTicket) {
            TableSoft.ReporteWS.generarReporteTicketRequest inValue = new TableSoft.ReporteWS.generarReporteTicketRequest();
            inValue.idTicket = idTicket;
            return ((TableSoft.ReporteWS.ReporteWS)(this)).generarReporteTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ReporteWS.generarReporteTicketUrgenciaResponse TableSoft.ReporteWS.ReporteWS.generarReporteTicketUrgencia(TableSoft.ReporteWS.generarReporteTicketUrgenciaRequest request) {
            return base.Channel.generarReporteTicketUrgencia(request);
        }
        
        public byte[] generarReporteTicketUrgencia(TableSoft.ReporteWS.urgencia objUrgencia, System.DateTime fechaIni, System.DateTime fechaFin) {
            TableSoft.ReporteWS.generarReporteTicketUrgenciaRequest inValue = new TableSoft.ReporteWS.generarReporteTicketUrgenciaRequest();
            inValue.objUrgencia = objUrgencia;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            TableSoft.ReporteWS.generarReporteTicketUrgenciaResponse retVal = ((TableSoft.ReporteWS.ReporteWS)(this)).generarReporteTicketUrgencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketUrgenciaResponse> TableSoft.ReporteWS.ReporteWS.generarReporteTicketUrgenciaAsync(TableSoft.ReporteWS.generarReporteTicketUrgenciaRequest request) {
            return base.Channel.generarReporteTicketUrgenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketUrgenciaResponse> generarReporteTicketUrgenciaAsync(TableSoft.ReporteWS.urgencia objUrgencia, System.DateTime fechaIni, System.DateTime fechaFin) {
            TableSoft.ReporteWS.generarReporteTicketUrgenciaRequest inValue = new TableSoft.ReporteWS.generarReporteTicketUrgenciaRequest();
            inValue.objUrgencia = objUrgencia;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            return ((TableSoft.ReporteWS.ReporteWS)(this)).generarReporteTicketUrgenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.ReporteWS.generarReporteTicketCategoriaResponse TableSoft.ReporteWS.ReporteWS.generarReporteTicketCategoria(TableSoft.ReporteWS.generarReporteTicketCategoriaRequest request) {
            return base.Channel.generarReporteTicketCategoria(request);
        }
        
        public byte[] generarReporteTicketCategoria(TableSoft.ReporteWS.categoria objCategoria, System.DateTime fechaIni, System.DateTime fechaFin) {
            TableSoft.ReporteWS.generarReporteTicketCategoriaRequest inValue = new TableSoft.ReporteWS.generarReporteTicketCategoriaRequest();
            inValue.objCategoria = objCategoria;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            TableSoft.ReporteWS.generarReporteTicketCategoriaResponse retVal = ((TableSoft.ReporteWS.ReporteWS)(this)).generarReporteTicketCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketCategoriaResponse> TableSoft.ReporteWS.ReporteWS.generarReporteTicketCategoriaAsync(TableSoft.ReporteWS.generarReporteTicketCategoriaRequest request) {
            return base.Channel.generarReporteTicketCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.ReporteWS.generarReporteTicketCategoriaResponse> generarReporteTicketCategoriaAsync(TableSoft.ReporteWS.categoria objCategoria, System.DateTime fechaIni, System.DateTime fechaFin) {
            TableSoft.ReporteWS.generarReporteTicketCategoriaRequest inValue = new TableSoft.ReporteWS.generarReporteTicketCategoriaRequest();
            inValue.objCategoria = objCategoria;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            return ((TableSoft.ReporteWS.ReporteWS)(this)).generarReporteTicketCategoriaAsync(inValue);
        }
    }
}
