//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSoft.BibliotecaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", ConfigurationName="BibliotecaWS.BibliotecaWS")]
    public interface BibliotecaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/insertarBibliotecaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/insertarBibliotecaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.BibliotecaWS.insertarBibliotecaResponse insertarBiblioteca(TableSoft.BibliotecaWS.insertarBibliotecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/insertarBibliotecaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/insertarBibliotecaResponse")]
        System.Threading.Tasks.Task<TableSoft.BibliotecaWS.insertarBibliotecaResponse> insertarBibliotecaAsync(TableSoft.BibliotecaWS.insertarBibliotecaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/listarBibliotecasRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/listarBibliotecasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.BibliotecaWS.listarBibliotecasResponse listarBibliotecas(TableSoft.BibliotecaWS.listarBibliotecasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/listarBibliotecasRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/listarBibliotecasResponse")]
        System.Threading.Tasks.Task<TableSoft.BibliotecaWS.listarBibliotecasResponse> listarBibliotecasAsync(TableSoft.BibliotecaWS.listarBibliotecasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/eliminarBibliotecaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/eliminarBibliotecaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.BibliotecaWS.eliminarBibliotecaResponse eliminarBiblioteca(TableSoft.BibliotecaWS.eliminarBibliotecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/eliminarBibliotecaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/eliminarBibliotecaResponse")]
        System.Threading.Tasks.Task<TableSoft.BibliotecaWS.eliminarBibliotecaResponse> eliminarBibliotecaAsync(TableSoft.BibliotecaWS.eliminarBibliotecaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/actualizarBibliotecaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/actualizarBibliotecaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TableSoft.BibliotecaWS.actualizarBibliotecaResponse actualizarBiblioteca(TableSoft.BibliotecaWS.actualizarBibliotecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/actualizarBibliotecaRequest", ReplyAction="http://services.tablesoft.pucp.edu.pe/BibliotecaWS/actualizarBibliotecaResponse")]
        System.Threading.Tasks.Task<TableSoft.BibliotecaWS.actualizarBibliotecaResponse> actualizarBibliotecaAsync(TableSoft.BibliotecaWS.actualizarBibliotecaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/")]
    public partial class biblioteca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abreviaturaField;
        
        private bool activoField;
        
        private int bibliotecaIdField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
                this.RaisePropertyChanged("abreviatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int bibliotecaId {
            get {
                return this.bibliotecaIdField;
            }
            set {
                this.bibliotecaIdField = value;
                this.RaisePropertyChanged("bibliotecaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarBiblioteca", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarBibliotecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.BibliotecaWS.biblioteca objBiblioteca;
        
        public insertarBibliotecaRequest() {
        }
        
        public insertarBibliotecaRequest(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            this.objBiblioteca = objBiblioteca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarBibliotecaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarBibliotecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarBibliotecaResponse() {
        }
        
        public insertarBibliotecaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarBibliotecas", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarBibliotecasRequest {
        
        public listarBibliotecasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarBibliotecasResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarBibliotecasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.BibliotecaWS.biblioteca[] @return;
        
        public listarBibliotecasResponse() {
        }
        
        public listarBibliotecasResponse(TableSoft.BibliotecaWS.biblioteca[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarBiblioteca", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarBibliotecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.BibliotecaWS.biblioteca objBiblioteca;
        
        public eliminarBibliotecaRequest() {
        }
        
        public eliminarBibliotecaRequest(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            this.objBiblioteca = objBiblioteca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarBibliotecaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarBibliotecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarBibliotecaResponse() {
        }
        
        public eliminarBibliotecaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarBiblioteca", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarBibliotecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TableSoft.BibliotecaWS.biblioteca objBiblioteca;
        
        public actualizarBibliotecaRequest() {
        }
        
        public actualizarBibliotecaRequest(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            this.objBiblioteca = objBiblioteca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarBibliotecaResponse", WrapperNamespace="http://services.tablesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarBibliotecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tablesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarBibliotecaResponse() {
        }
        
        public actualizarBibliotecaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BibliotecaWSChannel : TableSoft.BibliotecaWS.BibliotecaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BibliotecaWSClient : System.ServiceModel.ClientBase<TableSoft.BibliotecaWS.BibliotecaWS>, TableSoft.BibliotecaWS.BibliotecaWS {
        
        public BibliotecaWSClient() {
        }
        
        public BibliotecaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BibliotecaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibliotecaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibliotecaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.BibliotecaWS.insertarBibliotecaResponse TableSoft.BibliotecaWS.BibliotecaWS.insertarBiblioteca(TableSoft.BibliotecaWS.insertarBibliotecaRequest request) {
            return base.Channel.insertarBiblioteca(request);
        }
        
        public int insertarBiblioteca(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            TableSoft.BibliotecaWS.insertarBibliotecaRequest inValue = new TableSoft.BibliotecaWS.insertarBibliotecaRequest();
            inValue.objBiblioteca = objBiblioteca;
            TableSoft.BibliotecaWS.insertarBibliotecaResponse retVal = ((TableSoft.BibliotecaWS.BibliotecaWS)(this)).insertarBiblioteca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.BibliotecaWS.insertarBibliotecaResponse> TableSoft.BibliotecaWS.BibliotecaWS.insertarBibliotecaAsync(TableSoft.BibliotecaWS.insertarBibliotecaRequest request) {
            return base.Channel.insertarBibliotecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.BibliotecaWS.insertarBibliotecaResponse> insertarBibliotecaAsync(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            TableSoft.BibliotecaWS.insertarBibliotecaRequest inValue = new TableSoft.BibliotecaWS.insertarBibliotecaRequest();
            inValue.objBiblioteca = objBiblioteca;
            return ((TableSoft.BibliotecaWS.BibliotecaWS)(this)).insertarBibliotecaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.BibliotecaWS.listarBibliotecasResponse TableSoft.BibliotecaWS.BibliotecaWS.listarBibliotecas(TableSoft.BibliotecaWS.listarBibliotecasRequest request) {
            return base.Channel.listarBibliotecas(request);
        }
        
        public TableSoft.BibliotecaWS.biblioteca[] listarBibliotecas() {
            TableSoft.BibliotecaWS.listarBibliotecasRequest inValue = new TableSoft.BibliotecaWS.listarBibliotecasRequest();
            TableSoft.BibliotecaWS.listarBibliotecasResponse retVal = ((TableSoft.BibliotecaWS.BibliotecaWS)(this)).listarBibliotecas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.BibliotecaWS.listarBibliotecasResponse> TableSoft.BibliotecaWS.BibliotecaWS.listarBibliotecasAsync(TableSoft.BibliotecaWS.listarBibliotecasRequest request) {
            return base.Channel.listarBibliotecasAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.BibliotecaWS.listarBibliotecasResponse> listarBibliotecasAsync() {
            TableSoft.BibliotecaWS.listarBibliotecasRequest inValue = new TableSoft.BibliotecaWS.listarBibliotecasRequest();
            return ((TableSoft.BibliotecaWS.BibliotecaWS)(this)).listarBibliotecasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.BibliotecaWS.eliminarBibliotecaResponse TableSoft.BibliotecaWS.BibliotecaWS.eliminarBiblioteca(TableSoft.BibliotecaWS.eliminarBibliotecaRequest request) {
            return base.Channel.eliminarBiblioteca(request);
        }
        
        public int eliminarBiblioteca(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            TableSoft.BibliotecaWS.eliminarBibliotecaRequest inValue = new TableSoft.BibliotecaWS.eliminarBibliotecaRequest();
            inValue.objBiblioteca = objBiblioteca;
            TableSoft.BibliotecaWS.eliminarBibliotecaResponse retVal = ((TableSoft.BibliotecaWS.BibliotecaWS)(this)).eliminarBiblioteca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.BibliotecaWS.eliminarBibliotecaResponse> TableSoft.BibliotecaWS.BibliotecaWS.eliminarBibliotecaAsync(TableSoft.BibliotecaWS.eliminarBibliotecaRequest request) {
            return base.Channel.eliminarBibliotecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.BibliotecaWS.eliminarBibliotecaResponse> eliminarBibliotecaAsync(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            TableSoft.BibliotecaWS.eliminarBibliotecaRequest inValue = new TableSoft.BibliotecaWS.eliminarBibliotecaRequest();
            inValue.objBiblioteca = objBiblioteca;
            return ((TableSoft.BibliotecaWS.BibliotecaWS)(this)).eliminarBibliotecaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TableSoft.BibliotecaWS.actualizarBibliotecaResponse TableSoft.BibliotecaWS.BibliotecaWS.actualizarBiblioteca(TableSoft.BibliotecaWS.actualizarBibliotecaRequest request) {
            return base.Channel.actualizarBiblioteca(request);
        }
        
        public int actualizarBiblioteca(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            TableSoft.BibliotecaWS.actualizarBibliotecaRequest inValue = new TableSoft.BibliotecaWS.actualizarBibliotecaRequest();
            inValue.objBiblioteca = objBiblioteca;
            TableSoft.BibliotecaWS.actualizarBibliotecaResponse retVal = ((TableSoft.BibliotecaWS.BibliotecaWS)(this)).actualizarBiblioteca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TableSoft.BibliotecaWS.actualizarBibliotecaResponse> TableSoft.BibliotecaWS.BibliotecaWS.actualizarBibliotecaAsync(TableSoft.BibliotecaWS.actualizarBibliotecaRequest request) {
            return base.Channel.actualizarBibliotecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TableSoft.BibliotecaWS.actualizarBibliotecaResponse> actualizarBibliotecaAsync(TableSoft.BibliotecaWS.biblioteca objBiblioteca) {
            TableSoft.BibliotecaWS.actualizarBibliotecaRequest inValue = new TableSoft.BibliotecaWS.actualizarBibliotecaRequest();
            inValue.objBiblioteca = objBiblioteca;
            return ((TableSoft.BibliotecaWS.BibliotecaWS)(this)).actualizarBibliotecaAsync(inValue);
        }
    }
}
